
name: Deploy to demo

on:
  workflow_dispatch:
  push:
    branches:
      - *

permissions:
  contents: read
  id-token: 'write'
  packages: read

jobs:

  deploy:

    name: Deploy to demo
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version
        id: version
        run: echo VERSION=$(git describe --exact-match --tags | sed 's/^v//') >> $GITHUB_OUTPUT

      - name: Build container
        run: make

      #   uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build container
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: false
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      #     file: Containerfile
      #     build-args: |
      #       KIND=demo

      # - id: auth
      #   name: Authenticate with Google Cloud
      #   uses: google-github-actions/auth@v0
      #   with:
      #     token_format: access_token
      #     workload_identity_provider: projects/514167726704/locations/global/workloadIdentityPools/deploy/providers/deploy
      #     service_account: deploy@kalntera-demo.iam.gserviceaccount.com
      #     access_token_lifetime: 900s
      #     create_credentials_file: true

      # - name: Login to Artifact Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: us-central1-docker.pkg.dev
      #     username: oauth2accesstoken
      #     password: ${{ steps.auth.outputs.access_token }}

      # - name: Install Pulumi
      #   run: cd pulumi && npm install

      # - name: Applying infrastructure 🚀🙏
      #   uses: pulumi/actions@v3
      #   with:
      #     command: up
      #     stack-name: demo
      #     work-dir: pulumi
      #     cloud-url: gs://kalntera-deploy/cybersec-ai/demo
      #   env:
      #     PULUMI_CONFIG_PASSPHRASE: ""
      #     IMAGE_VERSION: ${{ steps.version.outputs.VERSION }}


